# Revisão Gestão da Segurança da Informação - 08/09/2026

## Governança de TI - Alinhamento Estratégico

#### TOMO 6 - Questão 7

Leia o texto a seguir. 

>>> A Política de Segurança é uma declaração que estabelece a hierarquia dos riscos da informação e identifica metas de segurança aceitáveis, assim como mecanismos para atingi-las. Uma das formas de implementá-la é seguir os passos para a certificação ISO 27001, que é uma norma de vigência internacional, cujo objetivo é determinar as diretrizes necessárias para uma gestão de segurança da informação nas organizações, sejam elas especializadas nesse tipo de serviço, sejam aquelas que tenham um setor interno dedicado à proteção de seus dados.

LAUDON, K. C; LAUDON, J. P. Sistemas de informação gerenciais. 11. ed. São Paulo: Pearson Prentice Hall (com adaptações).

Considerando as informações do texto, avalie as asserções e a relação proposta entre elas.

|  |
|------------------------------------------------------------------------|
| I. A política de segurança dá origem a outras políticas que determinam o uso aceitável dos recursos de informação da empresa e quais membros terão acesso a esses ativos. |
| **PORQUE** |
| II\. A política de uso aceitável define os usos aceitáveis dos recursos de informação e dos equipamentos de informática da empresa, incluindo computadores de mesa e laptops, dispositivos sem fio, telefones e internet. |

A respeito dessas asserções, assinale a alternativa correta.

|  |
|------------------------------------------------------------------------|
| A) As asserções I e II são verdadeiras, e a asserção II justifica a I. |
| B) As asserções I e II são verdadeiras, e a asserção II não justifica a I. |
| C) A asserção I é verdadeira, e a II é uma proposição falsa. |
| D) A asserção I é falsa, e a II é uma proposição verdadeira. |
| E) As asserções I e II são falsas. |

**Avaliação da Questão: Política de segurança para a informação**

Semelhante à questão anterior, a presente questão aborda um assunto relativo à segurança da informação. A principal referência normativa para sistemas de gestão de segurança da informação é a **ABNT NBR ISO/IEC 27001:2022**, Versão Corrigida:2023, que estabelece requisitos para o **SGSI**. Para os controles de segurança da informação, a referência complementar é a **ABNT NBR ISO/IEC 27002:2022**.

A **NBR ISO/IEC 27001:2022** fornece às empresas os requisitos para

-   estabelecer;
-   implementar;
-   manter; e
-   melhorar continuamente;

um **Sistema de Gestão de Segurança da Informação (SGSI)**. Ela foi desenvolvida para que as empresas possam **gerenciar riscos** e proteger, contra ameaças, os **ativos** de **informações financeiras**, de **propriedade intelectual** ou de **detalhes de funcionários**, por exemplo.

No quesito operação, essa norma define que a organização deve planejar, implementar e controlar os processos, os produtos e os serviços necessários, incluindo eventuais mudanças relacionadas ao pessoal e à infraestrutura, além de prover ações destinadas à avaliação e ao tratamento dos seus riscos.

Na **ABNT NBR ISO/IEC 27001:2022**, o Anexo A apresenta **controles de referência** para a segurança da informação. A **ABNT NBR ISO/IEC 27002:2022** detalha esses controles. Entre eles, o **controle 5.10** trata do **uso aceitável da informação e de outros ativos associados**, estabelecendo que regras de uso aceitável e **procedimentos** de manuseio devem ser **identificados**, **documentados** e **implementados**.

### Resposta:

- Alternativa "A"

## Referências Bibliográficas:

- ASSOCIAÇÃO BRASILEIRA DE NORMAS TÉCNICAS – ABNT. ABNT NBR ISO/IEC 27001:2022, Versão Corrigida:2023. Rio de Janeiro: ABNT, 2023.
- ASSOCIAÇÃO BRASILEIRA DE NORMAS TÉCNICAS – ABNT. ABNT NBR ISO/IEC 27002:2022. Rio de Janeiro: ABNT, 2022.
- FONTES, E. Políticas e Normas para a Segurança da Informação. Rio de Janeiro: Brasport, 2012.
- INTERNATIONAL ORGANIZATION FOR STANDARDIZATION. ISO/IEC 27001:2022/Amd 1:2024. Information security, cybersecurity and privacy protection — Information security management systems — Requirements — Amendment 1: Climate action changes. Geneva: ISO, 2024.
- LAUDON, K. C; LAUDON, J. P. Sistemas de informação gerenciais – Administrando a empresa digital. 17. ed. Porto Alegre: Bookman, 2023.
- NEVES, C. S. F. Universo Segurança da Informação: NBR ISO/IEC 27001:2022. Disponível em <https://www.estrategiaconcursos.com.br/blog/seguranca-informacao-iso-27001-2022/>. Acesso em 19 abr. 2026.
- PEGETTI, A. Gestão de segurança da informação. São Paulo: Senac, 2023.

